name: deploy-toy-website-environments
concurrency: toy-company

on: 
  push:
    branches: 
      - main
  workflow_dispatch:

env:
  AZURE_RESOURCEGROUP_NAME: ToyWebsiteTest
  ENVIRONMENT_TYPE: Test

jobs:
  # Lint the Bicep file
  lint: 
    uses: thepaulmacca/toy-website-environments/.github/workflows/lint.yml@main

  # Deploy to the Test environment
  deploy-test:
    uses: thepaulmacca/toy-website-environments/.github/workflows/deploy.yml@main
    needs: lint
    with:
      environmentType: Test
      resourceGroupName: rg-toywebsite-test
      reviewApiUrl: https://sandbox.contoso.com/reviews
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_TEST }}
      reviewApiKey: ${{ secrets.REVIEW_API_KEY_TEST }}
  
  # Deploy to the production environment.
  deploy-production:
    uses: thepaulmacca/toy-website-environments/.github/workflows/deploy.yml@main
    needs: deploy-test
    with:
      environmentType: Production
      resourceGroupName: rg-toywebsite-prod
      reviewApiUrl: https://api.contoso.com/reviews
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_PRODUCTION }}
      reviewApiKey: ${{ secrets.REVIEW_API_KEY_PRODUCTION }}
